In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4]

In [4]:
a[2]

3

In [5]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [6]:
dd[0][2]

3

# Tensor Axes Examples

In [7]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

Each element along the first axes is an array

In [8]:
dd[0]

[1, 2, 3]

In [9]:
dd[1]

[4, 5, 6]

In [10]:
dd[2]

[7, 8, 9]

Each element along the second axes is number

In [11]:
dd[0][0]

1

In [12]:
dd[1][0]

4

In [13]:
dd[2][0]

7

In [16]:
dd[0][1]

2

In [17]:
dd[1][1]

5

In [18]:
dd[2][1]

8

In [19]:
dd[0][2]

3

In [20]:
dd[1][2]

6

In [21]:
dd[2][2]

9

Shape of a tensor

In [22]:
#length of each axes is the shape of a tensor
dd=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [23]:
#To know the shape of a tensor, we create a tensor object
t = tf.constant(dd) # constant is a function that helps to a constant tensor
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [24]:
type(t) #to get the type of object

tensorflow.python.framework.ops.EagerTensor

In [25]:
#Now we have a tensor object, now we can see the tensor's shape
t.shape

TensorShape([3, 3])

# Tensor Operaton Types

Reshaping a tensor in tensorflow

In [26]:
t = tf.constant([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]],
dtype=tf.float32) #also mention the data type we want in the tensor

In [27]:
t

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]], dtype=float32)>

In [29]:
reshaped_tensor = tf.reshape(t,[4,3])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 2. 2.]
 [2. 2. 3.]
 [3. 3. 3.]], shape=(4, 3), dtype=float32)


In [30]:
reshaped_tensor = tf.reshape(t,[2,6])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [31]:
reshaped_tensor = tf.reshape(t,[1,12])
print(reshaped_tensor)

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [32]:
reshaped_tensor = tf.reshape(t,[2,2,3])
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


# Change Shape by sqeezing and unsqeezing

In [33]:
print(tf.reshape(t,[1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [34]:
print(tf.reshape(t,[1,12]).shape)

(1, 12)


In [36]:
print(tf.squeeze(tf.reshape(t,[1,12])))

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [37]:
print(tf.squeeze(tf.reshape(t,[1,12])).shape)

(12,)


In [38]:
rescaled_tensor = tf.reshape(t,[2,2,3])
print(rescaled_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


In [40]:
print(tf.squeeze(tf.reshape(t,[2,2,3])))

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


In [41]:
print(tf.squeeze(tf.reshape(t,[2,2,3])).shape)

(2, 2, 3)


# Flatten a tensor

In [46]:
def flatten(t):
    t = tf.reshape(1,-1)
    t = tf.squeeze(t)
    return t

In [50]:
t = tf.ones([4,3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [51]:
flatten(t)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Concatenating Tensor

In [52]:
t1 = tf.constant([
    [1,2],
    [3,4]
])

t2 = tf.constant([
    [5,6],
    [7,8]
])

In [53]:
tf.concat((t1,t2),axis=0) #concat() helps to concat according to the axis

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [54]:
tf.concat((t1,t2),axis=1) #concat() helps to concat according to the axis

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])>

In [55]:
tf.concat((t1,t2),axis=0).shape

TensorShape([4, 2])

In [56]:
tf.concat((t1,t2),axis=1).shape

TensorShape([2, 4])

# Rank - 0 Tensor Scalar

In [57]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


# Vector Rank - 1 Tensor

In [58]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


# Matrix Rank - 2 Tensor

In [59]:
#If we want to be specific, we can set the dtype at creation time.
rank_2_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


# Tensor with 3 axes - Rank 3 Tensor

In [60]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
    [5,6,7,8,9]],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,29]]
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


# Tensor to Numpy Array

In [61]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [62]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

# Math on tensors

In [63]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,1],
                [1,1]])

In [64]:
print(tf.add(a,b), '\n')

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 



In [66]:
print(tf.multiply(a,b), '\n')

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 



In [67]:
print(tf.matmul(a,b), '\n')

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [68]:
print(a+b, '\n') # element wise addition

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 



In [69]:
print(a*b, '\n') # element wise mutiplication

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 



In [70]:
print(a @ b, '\n') # matrix multiplication

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



# About Shape

In [71]:
rank_4_tensor = tf.zeros([3,2,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [72]:
print('Type of every element:', rank_4_tensor.dtype)

Type of every element: <dtype: 'float32'>


In [73]:
print('Number of dimensions:', rank_4_tensor.ndim)

Number of dimensions: 4


In [74]:
print('Shape of tensor:', rank_4_tensor.shape)

Shape of tensor: (3, 2, 4, 5)


In [75]:
print('Element along axis 0 of tensor:', rank_4_tensor.shape[0])

Element along axis 0 of tensor: 3


In [76]:
print('Element along axis 1 of tensor:', rank_4_tensor.shape[1])

Element along axis 1 of tensor: 2


In [77]:
print('Element along last axis of tensor:', rank_4_tensor.shape[-1])

Element along last axis of tensor: 5


# Indexing

Single Axes Indexing

In [78]:
rank_1_tensor = tf.constant([0,1,1,2,3,5,8,13,21,34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


Indexing with a scalar removes the dimension

In [79]:
print('First:', rank_1_tensor[0].numpy())

First: 0


In [80]:
print('Second:', rank_1_tensor[1].numpy())

Second: 1


In [81]:
print('Last:', rank_1_tensor[-1].numpy())

Last: 34


Indexing with a colon keeps the dimension

In [84]:
print('Everything:',rank_1_tensor[:].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]


In [85]:
print('Before 4:',rank_1_tensor[:4].numpy())

Before 4: [0 1 1 2]


In [86]:
print('From 4 to the end:',rank_1_tensor[4:].numpy())

From 4 to the end: [ 3  5  8 13 21 34]


In [87]:
print('From 2, before 7 :',rank_1_tensor[2:7].numpy())

From 2, before 7 : [1 2 3 5 8]


In [88]:
print('Every other item:',rank_1_tensor[::2].numpy())

Every other item: [ 0  1  3  8 21]


In [89]:
print('Reversed:',rank_1_tensor[::-1].numpy())

Reversed: [34 21 13  8  5  3  2  1  1  0]


In [90]:
print('Reversed:',rank_1_tensor[::-2].numpy())

Reversed: [34 13  5  2  1]


Multi Axes Indexing

In [91]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


Passing an integer returns a scalar

In [92]:
print(rank_2_tensor[1,1].numpy())

4.0


Index can be done in any combination of integers and slices

In [94]:
#get row and column tensors
print('Second Row:', rank_2_tensor[1,:].numpy())

Second Row: [3. 4.]


In [95]:
print('Second Column:', rank_2_tensor[:,1].numpy())

Second Column: [2. 4. 6.]


In [96]:
print('Last Row:', rank_2_tensor[-1,:].numpy())

Last Row: [5. 6.]


In [97]:
print('Last Column:', rank_2_tensor[:,-1].numpy())

Last Column: [2. 4. 6.]


In [98]:
print('First Item in the last column:', rank_2_tensor[0,-1].numpy())

First Item in the last column: 2.0


In [99]:
print('Skip the first row:', rank_2_tensor[1:,:].numpy())

Skip the first row: [[3. 4.]
 [5. 6.]]


An example of 3 axis tensor

In [101]:
print(rank_3_tensor[:,:,4].numpy()) #selecting the last features along all locations in each batch

[[ 4  9]
 [14 19]
 [24 29]]


# Manipulating shapes

Reshaping a tensor is of great utility

In [102]:
var_x = tf.Variable(tf.constant([[1],[2],[3]]))

In [103]:
print(var_x.shape)

(3, 1)


In [104]:
reshaped = tf.reshape(var_x,[1,3])

In [105]:
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [106]:
print(var_x.shape)

(3, 1)


In [107]:
print(reshaped.shape)

(1, 3)


In [108]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


As you flatten, you can in which order data is laid in memory

In [110]:
print(tf.reshape(rank_3_tensor,[-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


Use of tf.reshape is add or split axes

In [111]:
print(tf.reshape(rank_3_tensor,[3*2,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [112]:
print(tf.reshape(rank_3_tensor,[3,-1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


# More on Dtypes

Cast can be done from type to type

In [113]:
the_f64_tensor = tf.constant([2.2,3.3,4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
#now we can cast to uint8, loose precision
the_uint8_tensor= tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_uint8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)
